# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Akyos\BuilderBundle\:
        resource: '../../../../lib/BuilderBundle/*'
        tags: ['controller.service_arguments']
        public: true

    render.builder:
        alias: Akyos\BuilderBundle\Service\Builder
        public: true

    component.row:
        alias: Akyos\BuilderBundle\Components\Row\RowComponentController
        public: true

    component.col:
        alias: Akyos\BuilderBundle\Components\Col\ColComponentController
        public: true

    component.button:
        alias: Akyos\BuilderBundle\Components\Button\ButtonComponentController
        public: true

    component.image:
        alias: Akyos\BuilderBundle\Components\Image\ImageComponentController
        public: true

    component.text:
        alias: Akyos\BuilderBundle\Components\Text\TextComponentController
        public: true
