# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Akyos\BuilderBundle\:
        resource: './../../*'
        tags: ['controller.service_arguments']
        public: true

    render.builder:
        alias: Akyos\BuilderBundle\Service\Builder
        public: true

    component.row:
        alias: Akyos\BuilderBundle\Components\Row\RowComponentController
        public: true

    component.col:
        alias: Akyos\BuilderBundle\Components\Col\ColComponentController
        public: true

    component.button:
        alias: Akyos\BuilderBundle\Components\Button\ButtonComponentController
        public: true

    component.image:
        alias: Akyos\BuilderBundle\Components\Image\ImageComponentController
        public: true

    component.text:
        alias: Akyos\BuilderBundle\Components\Text\TextComponentController
        public: true

    component.slider:
        alias: Akyos\BuilderBundle\Components\Slider\SliderComponentController
        public: true
    component.slide:
        alias: Akyos\BuilderBundle\Components\Slide\SlideComponentController
        public: true
    component.title:
        alias: Akyos\BuilderBundle\Components\Title\TitleComponentController
        public: true
    component.icon_title_box:
        alias: Akyos\BuilderBundle\Components\IconTitleBox\IconTitleBoxComponentController
        public: true
    component.last_news:
        alias: Akyos\BuilderBundle\Components\LastNews\LastNewsComponentController
        public: true
    component.news:
        alias: Akyos\BuilderBundle\Components\News\NewsComponentController
        public: true
    component.image_gallery:
        alias: Akyos\BuilderBundle\Components\ImageGallery\ImageGalleryComponentController
        public: true
    component.map:
        alias: Akyos\BuilderBundle\Components\Map\MapComponentController
        public: true
    component.form:
        alias: Akyos\BuilderBundle\Components\Form\FormComponentController
        public: true
